apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodatabase
  name: mongodatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodatabase
  template:
    metadata:
      labels:
        app: mongodatabase
    spec:
      containers:
      - image: mongo:5
        name: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-users
                key: database
 #         - name: MONGO_INITDB_ROOT_USERNAME
 #           valueFrom:
 #             secretKeyRef:
 #               name: msvc-users
 #               key: username
 #         - name: MONGO_INITDB_ROOT_PASSWORD
 #           valueFrom:
 #             secretKeyRef:
 #               name: msvc-users
 #               key: password               
        volumeMounts:
         - name: data-mongo
           mountPath: /data/db
      volumes:
        - name: data-mongo
          persistentVolumeClaim:
            claimName: mongo-pvc
            