version: "3.9"
services:
  mongodatabase:
    container_name: mongodatabase
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo:/data/db
    networks:
      - spring      
    
volumes:
  data-postgres:
    name: data-postgres
    
networks:
  spring:

        