apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
     storage: 1Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07829435b889e1ca4
