apiVersion: v1
kind: Service
metadata:
  name: mongodatabase
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodatabase
  sessionAffinity: None
  type: ClusterIP
